[workspace]
name = "work"

[[project]]
name = "selectus"
path = "../../work/selectus"

[[project.repo]]
path = "selectus-ms"

[[project.repo]]
path = "selectus-ui"

[[project.repo]]
path = "selectus-print-service"

[[project]]
name = "blackcove"
path = "../../work/blackcove"

[[project.repo]]
path = "blackcove-ms"

[[project.repo]]
path = "blackcove-studio"

[[project.repo]]
path = "blackcove-survey"

[[project]]
name = "keel"
path = "../../work/keel"

[[project.repo]]
path = "keel-ms-rest"

[[project.repo]]
path = "keel-ui-rest"

[[project.repo]]
path = "keel-falconet"

[display]
icons = true
group_docs = true
group_folders = true
